[package]
name = "omnidork"
version = "0.1.0"
edition = "2021" # Use the latest stable edition

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
reqwest = { version = "0.12.4", features = ["json", "rustls-tls", "socks"] }
url = "2.1.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
regex = "1.10.5"
num-complex = "0.4.5"
nalgebra = "0.33.0"
rand = "0.8.5"
ipnet = "2.9.1"
scraper = "0.19.0"
flate2 = { version = "1.0.30", features = ["zlib"] }
futures = "0.3.30"
log = "0.4.21"
env_logger = "0.11.3"
base64 = "0.22.1"
chrono = "0.4.38"
urlencoding = "2.1.3"
primal = "0.3.3"  # For prime factorization
rayon = "1.10.0"  # For parallel processing