[package]
name = "omnidork"
version = "0.1.0"
edition = "2021" # Use the latest stable edition

[dependencies]
# Asynchronous runtime
tokio = { version = "1.37.0", features = ["full"] } # Use a recent version

# HTTP client
reqwest = { version = "0.12.4", features = ["json", "rustls-tls", "socks"] } # Add socks feature for proxies, use rustls-tls for wider compatibility
url = "2.1.3" # For URL parsing

# Data serialization/deserialization
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

# Regular expressions
regex = "1.10.5"

# Data structures and math

num-complex = "0.4.5" # For complex numbers
nalgebra = "0.33.0" # For linear algebra (matrices, vectors)
rand = "0.8.5" # For random number generation
ipnet = "2.9.1" # For IP network calculations

# HTML parsing (for proxy scanner and possibly dork results)
scraper = "0.19.0"

# Compression (for engine checkpoints)
flate2 = { version = "1.0.30", features = ["zlib"] } # Explicitly enable a backend if needed, or use default

# Asynchronous streams
futures = "0.3.30"

# Logging
log = "0.4.21"
env_logger = "0.11.3" # For basic logging setup

# Base64 encoding/decoding (for checkpoints)
base64 = "0.22.1"

# Timestamping (needed for some structs)
chrono = "0.4.38"

# URL encoding (for dork engine)
urlencoding = "2.1.3"


# Feature to enable/disable quantum/persistence based on compile time
# This is more advanced, for now we'll handle it with runtime flags in main.rs
# [features]
# quantum = []
# persistence = []

# [dev-dependencies] # Add dev dependencies for testing utilities if needed